language: python
python:
  - "3.8.2"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install wheel
  - pip install -e .
script: pytest
after_success:
  - coverage run -m pytest -q tests/test_wallet.py
  - coverage report -m
  - coverage html
